//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USBDevices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USBDevices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10006|YUEN DA ELECTRONIC PRODUCTS FACTORY
        ///10013|Gionee Communication Equipment Co., Ltd. ShenZhen
        ///10018|FOOSUNG TECH
        ///10022|Universal Electronics Inc. (DBA: TVIEW)
        ///1003|Atmel Corporation
        ///1006|Mitsumi
        ///1008|Hewlett Packard
        ///10112|M31 Technology Corp.
        ///10113|Liteconn Co., Ltd.
        ///10120|Sanwin (HK) Electronic Technology Co., Ltd.
        ///10121|Suzhou WEIJU Electronics Technology Co., Ltd.
        ///10144|Mondokey Limited
        ///10149|Advantest Corporation
        ///10150|iRobot Corporation
        ///10182|Shenzhen Huiding Technology Co. Ltd.
        ///1020|Elitegroup Com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usbVendors {
            get {
                return ResourceManager.GetString("usbVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001  Fry&apos;s Electronics
        ///	142b  Arbiter Systems, Inc.
        ///	7778  Counterfeit flash drive [Kingston]
        ///0002  Ingram
        ///0003  Club Mac
        ///0004  Nebraska Furniture Mart
        ///0011  Unknown
        ///	7788  Flash mass storage drive
        ///0053  Planex
        ///	5301  GW-US54ZGL 802.11bg
        ///0079  DragonRise Inc.
        ///	0006  PC TWIN SHOCK Gamepad
        ///	0011  Gamepad
        ///0105  Trust International B.V.
        ///	145f  NW-3100 802.11b/g 54Mbps Wireless Network Adapter [zd1211]
        ///0145  Unknown
        ///	0112  Card Reader
        ///017c  MLK
        ///	145f  Trust Deskset
        ///0200  TP-Link
        ///	0201  MA180 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vendorproductlist {
            get {
                return ResourceManager.GetString("vendorproductlist", resourceCulture);
            }
        }
    }
}
